// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/*" | "/dashboard" | "/profile";
  };
  "../src/pages/login/Login.jsx": {
    id: "../src/pages/login/Login";
    page: "/";
  };
  "../src/pages/notFound/NotFound.jsx": {
    id: "../src/pages/notFound/NotFound";
    page: "/*";
  };
  "../src/component/ProtectedRoute.jsx": {
    id: "../src/component/ProtectedRoute";
    page: "/dashboard" | "/profile";
  };
  "../src/pages/dashboard/Dashboard.jsx": {
    id: "../src/pages/dashboard/Dashboard";
    page: "/dashboard";
  };
  "../src/pages/profile/Profile.jsx": {
    id: "../src/pages/profile/Profile";
    page: "/profile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "../src/pages/login/Login": unknown;
  "../src/pages/notFound/NotFound": unknown;
  "../src/component/ProtectedRoute": unknown;
  "../src/pages/dashboard/Dashboard": unknown;
  "../src/pages/profile/Profile": unknown;
};